// OpenStreetMap (Overpass API) から国分町エリアの店舗を取得し、D1 の venues に投入する。
// データは © OpenStreetMap contributors (ODbL)。README の出典表記を残すこと。
//
// 使い方:
//   node scripts/import-venues.mjs            # ローカルD1へ
//   node scripts/import-venues.mjs --remote   # 本番D1へ
//   オプション: --limit=60 (中心から近い順の件数上限) / --radius=300 (m)
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const args = process.argv.slice(2);
const remote = args.includes('--remote');
const opt = (name, fallback) => {
  const a = args.find((x) => x.startsWith(`--${name}=`));
  return a ? Number(a.split('=')[1]) : fallback;
};
const area = JSON.parse(readFileSync(new URL('../../shared/area.json', import.meta.url), 'utf8'));
const LIMIT = opt('limit', 250);
const RADIUS = opt('radius', area.radiusM + 50);
const PER_CELL = opt('percell', 2); // 約45mグリッドのセルあたり最大件数(密集の間引き)
const CENTER = { lat: area.lat, lng: area.lng };

// アプリの4カテゴリへの近似マッピング
const CATEGORY = {
  bar: 'バー',
  pub: '居酒屋',
  restaurant: '居酒屋',
  cafe: 'カフェ',
  nightclub: 'ラウンジ',
};

function distanceM(lat, lng) {
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(lat - CENTER.lat);
  const dLng = toRad(lng - CENTER.lng);
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(CENTER.lat)) * Math.cos(toRad(lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * 6371000 * Math.asin(Math.sqrt(s));
}

const query = `[out:json][timeout:25];nwr(around:${RADIUS},${CENTER.lat},${CENTER.lng})[amenity~"^(bar|pub|restaurant|cafe|nightclub)$"];out center 500;`;
const res = await fetch('https://overpass-api.de/api/interpreter', {
  method: 'POST',
  headers: {
    'user-agent': 'yoawase-venue-import/1.0 (demo app)',
    'content-type': 'application/x-www-form-urlencoded',
  },
  body: new URLSearchParams({ data: query }).toString(),
});
if (!res.ok) throw new Error(`Overpass API error: ${res.status}`);
const json = await res.json();

const candidates = json.elements
  .filter((e) => e.tags?.name && CATEGORY[e.tags.amenity])
  .map((e) => ({
    id: `osm-${e.type}-${e.id}`,
    name: e.tags.name,
    category: CATEGORY[e.tags.amenity],
    lat: e.lat ?? e.center?.lat,
    lng: e.lon ?? e.center?.lon,
  }))
  .filter((v) => v.lat !== undefined && v.lng !== undefined);

// 「中心から近い順」だと外周が空白になるため、グリッドで空間的に間引いて
// エリア全体をまんべんなくカバーする。セル内では夜の店を優先する。
const CELL_DEG = 0.0004; // 緯度約45m
const PRIORITY = { バー: 0, ラウンジ: 0, 居酒屋: 1, カフェ: 2 };
const cells = new Map();
for (const v of candidates) {
  const key = `${Math.floor(v.lat / CELL_DEG)}:${Math.floor(v.lng / CELL_DEG)}`;
  const list = cells.get(key) ?? [];
  list.push(v);
  cells.set(key, list);
}
const venues = [...cells.values()]
  .flatMap((list) =>
    list
      .sort(
        (a, b) =>
          PRIORITY[a.category] - PRIORITY[b.category] ||
          distanceM(a.lat, a.lng) - distanceM(b.lat, b.lng),
      )
      .slice(0, PER_CELL),
  )
  .sort((a, b) => distanceM(a.lat, a.lng) - distanceM(b.lat, b.lng))
  .slice(0, LIMIT);

if (venues.length === 0) throw new Error('店舗が0件でした。Overpassの応答を確認してください。');

const esc = (s) => s.replace(/'/g, "''");
const idList = venues.map((v) => `'${v.id}'`).join(',');
const sql = [
  '-- generated by scripts/import-venues.mjs (© OpenStreetMap contributors, ODbL)',
  // 架空のシード店舗(v-*)と、今回のリストに含まれない過去インポート分を掃除する
  // (venuesを参照するチェックインも先に消す)
  "DELETE FROM checkins WHERE venue_id LIKE 'v-%';",
  "DELETE FROM venues WHERE id LIKE 'v-%';",
  `DELETE FROM checkins WHERE venue_id LIKE 'osm-%' AND venue_id NOT IN (${idList});`,
  `DELETE FROM venues WHERE id LIKE 'osm-%' AND id NOT IN (${idList});`,
  ...venues.map(
    (v) =>
      `INSERT INTO venues (id,name,category,lat,lng) VALUES ('${v.id}','${esc(v.name)}','${v.category}',${v.lat},${v.lng})` +
      ` ON CONFLICT(id) DO UPDATE SET name='${esc(v.name)}', category='${v.category}', lat=${v.lat}, lng=${v.lng};`,
  ),
].join('\n');

const outDir = path.join(process.cwd(), '.generated');
mkdirSync(outDir, { recursive: true });
const outFile = path.join(outDir, 'venues.sql');
writeFileSync(outFile, sql);

console.log(`${venues.length}件の店舗を ${remote ? 'リモート' : 'ローカル'} D1 に投入します...`);
execFileSync(
  'npx',
  ['wrangler', 'd1', 'execute', 'yoawase', remote ? '--remote' : '--local', '--file', outFile, '-y'],
  { stdio: 'inherit' },
);
console.log('完了。カテゴリ内訳:');
const counts = {};
for (const v of venues) counts[v.category] = (counts[v.category] ?? 0) + 1;
console.log(counts);
